[project]
name = "google-gemini-api-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.30.0",
    "chainlit>=2.9.2",
    "google-generativeai>=0.8.5",
    "python-dotenv>=1.2.1",
]
